use crate::kana::kana_struct::Kana;

pub fn hiragana() -> Vec<Kana> {
    vec![
        // Vocals
        Kana::new(vec!["a"], "a", "あ"),
        Kana::new(vec!["i"], "i", "い"),
        Kana::new(vec!["u"], "u", "う"),
        Kana::new(vec!["e"], "e", "え"),
        Kana::new(vec!["o"], "o", "お"),
        // K
        Kana::new(vec!["ka"], "ka", "か"),
        Kana::new(vec!["ki"], "ki", "き"),
        Kana::new(vec!["ku"], "ku", "く"),
        Kana::new(vec!["ke"], "ke", "け"),
        Kana::new(vec!["ko"], "ko", "こ"),
        // S
        Kana::new(vec!["sa"], "sa", "さ"),
        Kana::new(vec!["shi"], "shi", "し"),
        Kana::new(vec!["su"], "su", "す"),
        Kana::new(vec!["se"], "se", "せ"),
        Kana::new(vec!["so"], "so", "そ"),
        // T
        Kana::new(vec!["ta"], "ta", "た"),
        Kana::new(vec!["chi"], "chi", "ち"),
        Kana::new(vec!["tsu"], "tsu", "つ"),
        Kana::new(vec!["te"], "te", "て"),
        Kana::new(vec!["to"], "to", "と"),
        // N
        Kana::new(vec!["na"], "na", "な"),
        Kana::new(vec!["ni"], "ni", "に"),
        Kana::new(vec!["nu"], "nu", "ぬ"),
        Kana::new(vec!["ne"], "ne", "ね"),
        Kana::new(vec!["no"], "no", "の"),
        // H
        Kana::new(vec!["ha"], "ha", "は"),
        Kana::new(vec!["hi"], "hi", "ひ"),
        Kana::new(vec!["hu", "fu"], "fu", "ふ"),
        Kana::new(vec!["he"], "he", "へ"),
        Kana::new(vec!["ho"], "ho", "ほ"),
        // M
        Kana::new(vec!["ma"], "ma", "ま"),
        Kana::new(vec!["mi"], "mi", "み"),
        Kana::new(vec!["mu"], "mu", "む"),
        Kana::new(vec!["me"], "me", "め"),
        Kana::new(vec!["mo"], "mo", "も"),
        // Y
        Kana::new(vec!["ya"], "ya", "や"),
        Kana::new(vec!["yu"], "yu", "ゆ"),
        Kana::new(vec!["yo"], "yo", "よ"),
        // R
        Kana::new(vec!["ra"], "ra", "ら"),
        Kana::new(vec!["ri"], "ri", "り"),
        Kana::new(vec!["ru"], "ru", "る"),
        Kana::new(vec!["re"], "re", "れ"),
        Kana::new(vec!["ro"], "ro", "ろ"),
        // W
        Kana::new(vec!["wa"], "wa", "わ"),
        Kana::new(vec!["o"], "wo", "を"),
        // N
        Kana::new(vec!["n"], "n", "ん"),
        // G
        Kana::new(vec!["ga"], "ga", "が"),
        Kana::new(vec!["gi"], "gi", "ぎ"),
        Kana::new(vec!["gu"], "gu", "ぐ"),
        Kana::new(vec!["ge"], "ge", "げ"),
        Kana::new(vec!["go"], "go", "ご"),
        // Z/J
        Kana::new(vec!["za"], "za", "ず"),
        Kana::new(vec!["ji"], "ji", "じ"),
        Kana::new(vec!["zu"], "zu", "ず"),
        Kana::new(vec!["ze"], "ze", "ぜ"),
        Kana::new(vec!["zo"], "zo", "ぞ"),
        // D
        Kana::new(vec!["da"], "da", "だ"),
        Kana::new(vec!["ji"], "di", "ぢ"),
        Kana::new(vec!["zu"], "du", "づ"),
        Kana::new(vec!["de"], "de", "で"),
        Kana::new(vec!["do"], "do", "ど"),
        // B
        Kana::new(vec!["ba"], "ba", "ば"),
        Kana::new(vec!["bi"], "bi", "び"),
        Kana::new(vec!["bu"], "bu", "ぶ"),
        Kana::new(vec!["be"], "be", "べ"),
        Kana::new(vec!["bo"], "bo", "ぼ"),
        // P
        Kana::new(vec!["pa"], "pa", "ぱ"),
        Kana::new(vec!["pi"], "pi", "ぴ"),
        Kana::new(vec!["pu"], "pu", "ぷ"),
        Kana::new(vec!["pe"], "pe", "ぺ"),
        Kana::new(vec!["po"], "po", "ぽ"),
        // Combinations
        Kana::new(vec!["kya"], "kya", "きゃ"),
        Kana::new(vec!["kyu"], "kyu", "きゅ"),
        Kana::new(vec!["kyo"], "kyo", "きょ"),
        Kana::new(vec!["sha"], "sha", "しゃ"),
        Kana::new(vec!["shu"], "shu", "しゅ"),
        Kana::new(vec!["sho"], "sho", "しょ"),
        Kana::new(vec!["cha"], "cha", "ちゃ"),
        Kana::new(vec!["chu"], "chu", "ちゅ"),
        Kana::new(vec!["cho"], "cho", "ちょ"),
        Kana::new(vec!["nya"], "nya", "にゃ"),
        Kana::new(vec!["nyu"], "nyu", "にゅ"),
        Kana::new(vec!["nyo"], "nyo", "にょ"),
        Kana::new(vec!["hya"], "hya", "ひゃ"),
        Kana::new(vec!["hyu"], "hyu", "ひゅ"),
        Kana::new(vec!["hyo"], "hyo", "ひょ"),
        Kana::new(vec!["mya"], "mya", "みゃ"),
        Kana::new(vec!["myu"], "myu", "みゅ"),
        Kana::new(vec!["myo"], "myo", "みょ"),
        Kana::new(vec!["rya"], "rya", "りゃ"),
        Kana::new(vec!["ryu"], "ryu", "りゅ"),
        Kana::new(vec!["ryo"], "ryo", "りょ"),
        Kana::new(vec!["gya"], "gya", "ぎゃ"),
        Kana::new(vec!["gyu"], "gyu", "ぎゅ"),
        Kana::new(vec!["gyo"], "gyo", "ぎょ"),
        Kana::new(vec!["jya"], "jya", "じゃ"),
        Kana::new(vec!["jyu"], "jyu", "じゅ"),
        Kana::new(vec!["jyo"], "jyo", "じょ"),
        Kana::new(vec!["jya"], "dya", "ぢゃ"),
        Kana::new(vec!["jyu"], "dyu", "ぢゅ"),
        Kana::new(vec!["jyo"], "dyo", "ぢょ"),
        Kana::new(vec!["bya"], "bya", "びゃ"),
        Kana::new(vec!["byu"], "byu", "びゅ"),
        Kana::new(vec!["byo"], "byo", "びょ"),
        Kana::new(vec!["pya"], "pya", "ぴゃ"),
        Kana::new(vec!["pyu"], "pyu", "ぴゅ"),
        Kana::new(vec!["pyo"], "pyo", "ぴょ"),
    ]
}
