use crate::kana::kana_struct::Kana;

pub fn katakana() -> Vec<Kana> {
    vec![
        // Vocals
        Kana::new(vec!["a"],"a", "ア"),
        Kana::new(vec!["i"], "i", "イ"),
        Kana::new(vec!["u"], "u", "ウ"),
        Kana::new(vec!["e"], "e", "エ"),
        Kana::new(vec!["o"], "o", "オ"),
        // K
        Kana::new(vec!["ka"], "ka", "カ"),
        Kana::new(vec!["ki"], "ki", "キ"),
        Kana::new(vec!["ku"], "ku", "ク"),
        Kana::new(vec!["ke"], "ke", "ケ"),
        Kana::new(vec!["ko"], "ko", "コ"),
        // S
        Kana::new(vec!["sa"], "sa", "サ"),
        Kana::new(vec!["shi"], "shi", "シ"),
        Kana::new(vec!["su"], "su", "ス"),
        Kana::new(vec!["se"], "se", "セ"),        
        Kana::new(vec!["so"], "so", "ソ"),
        // T
        Kana::new(vec!["ta"], "ta", "タ"),
        Kana::new(vec!["chi"], "chi", "チ"),
        Kana::new(vec!["tsu"], "tsu", "ツ"),
        Kana::new(vec!["te"], "te", "テ"),
        Kana::new(vec!["to"], "to", "ト"),
        // N
        Kana::new(vec!["na"], "na", "ナ"),
        Kana::new(vec!["ni"], "ni", "ニ"),
        Kana::new(vec!["nu"], "nu", "ヌ"),
        Kana::new(vec!["ne"], "ne", "ネ"),
        Kana::new(vec!["no"], "no", "ノ"),
        // H
        Kana::new(vec!["ha"], "ha", "ハ"),
        Kana::new(vec!["hi"], "hi", "ヒ"),
        Kana::new(vec!["hu", "fu"], "fu", "フ"),
        Kana::new(vec!["he"], "he", "ヘ"),
        Kana::new(vec!["ho"], "ho", "ホ"),
        // M
        Kana::new(vec!["ma"], "ma", "マ"),        
        Kana::new(vec!["mi"], "mi", "ミ"),
        Kana::new(vec!["mu"], "mu", "ム"),
        Kana::new(vec!["me"], "me", "メ"),
        Kana::new(vec!["mo"], "mo", "モ"),
        // Y
        Kana::new(vec!["ya"], "ya", "ヤ"),
        Kana::new(vec!["yu"], "yu", "ユ"),
        Kana::new(vec!["yo"], "yo", "ヨ"),
        // R
        Kana::new(vec!["ra"], "ra", "ラ"),
        Kana::new(vec!["ri"], "ri", "リ"),
        Kana::new(vec!["ru"], "ru", "ル"),
        Kana::new(vec!["re"], "re", "レ"),
        Kana::new(vec!["ro"], "ro", "ロ"),
        // W
        Kana::new(vec!["wa"], "wa", "ワ"),
        Kana::new(vec!["o"], "wo", "ヲ"),
        // N
        Kana::new(vec!["n"], "n", "ン"),
        // G
        Kana::new(vec!["ga"], "ga", "ガ"),
        Kana::new(vec!["gi"], "gi", "ギ"),
        Kana::new(vec!["gu"], "gu", "グ"),
        Kana::new(vec!["ge"], "ge", "ケ"),
        Kana::new(vec!["go"], "go", "コ"),
        // Z/J
        Kana::new(vec!["za"], "za", "ザ"),
        Kana::new(vec!["ji"], "ji", "ジ"),
        Kana::new(vec!["zu"], "zu", "ズ"),
        Kana::new(vec!["ze"], "ze", "セ"),
        Kana::new(vec!["zo"], "zo", "ソ"),
        // D
        Kana::new(vec!["da"], "da", "ダ"),
        Kana::new(vec!["ji"], "di", "ヂ"),
        Kana::new(vec!["zu"], "du", "ヅ"),
        Kana::new(vec!["de"], "de", "デ"),
        Kana::new(vec!["do"], "do", "ド"),
        // B
        Kana::new(vec!["ba"], "ba", "バ"),
        Kana::new(vec!["bi"], "bi", "ビ"),
        Kana::new(vec!["bu"], "bu", "ブ"),
        Kana::new(vec!["be"], "be", "ベ"),
        Kana::new(vec!["bo"], "bo", "ボ"),
        // P
        Kana::new(vec!["pa"], "pa", "パ"),
        Kana::new(vec!["pi"], "pi", "ピ"),
        Kana::new(vec!["pu"], "pu", "プ"),
        Kana::new(vec!["pe"], "pe", "ペ"),
        Kana::new(vec!["po"], "po", "ポ"),
        // BW
        Kana::new(vec!["bwa"], "va", "ヴぁ"),
        Kana::new(vec!["bwi"], "vi", "ヴぃ"),
        Kana::new(vec!["bwu"], "vu", "ヴ"),
        Kana::new(vec!["bwe"], "ve", "ヴぇ"),
        Kana::new(vec!["bwo"], "vo", "ヴぉ"),
        // Combinations
        Kana::new(vec!["kya"], "kya", "キャ"),
        Kana::new(vec!["kyu"], "kyu", "キュ"),
        Kana::new(vec!["kyo"], "kyo", "キョ"),
        Kana::new(vec!["sha"], "sha", "シャ"),
        Kana::new(vec!["shu"], "shu", "シュ"),
        Kana::new(vec!["sho"], "sho", "ショ"),
        Kana::new(vec!["cha"], "cha", "チャ"),
        Kana::new(vec!["chu"], "chu", "チュ"),
        Kana::new(vec!["cho"], "cho", "チョ"),
        Kana::new(vec!["nya"], "nya", "ニャ"),
        Kana::new(vec!["nyu"], "nyu", "ニュ"),
        Kana::new(vec!["nyo"], "nyo", "ニョ"),
        Kana::new(vec!["hya"], "hya", "ヒャ"),
        Kana::new(vec!["hyu"], "hyu", "ヒュ"),
        Kana::new(vec!["hyo"], "hyo", "ヒョ"),
        Kana::new(vec!["mya"], "mya", "ミャ"),
        Kana::new(vec!["myu"], "myu", "ミュ"),
        Kana::new(vec!["myo"], "myo", "ミョ"),
        Kana::new(vec!["rya"], "rya", "リャ"),
        Kana::new(vec!["ryu"], "ryu", "リュ"),
        Kana::new(vec!["ryo"], "ryo", "リョ"),
        Kana::new(vec!["gya"], "gya", "ギャ"),
        Kana::new(vec!["gyu"], "gyu", "ギュ"),
        Kana::new(vec!["gyo"], "gyo", "ギョ"),
        Kana::new(vec!["jya"], "jya", "ジャ"),
        Kana::new(vec!["jyu"], "jyu", "ジュ"),
        Kana::new(vec!["jyo"], "jyo", "ジョ"),
        Kana::new(vec!["jya"], "dya", "デャ"),
        Kana::new(vec!["jyu"], "dyu", "デュ"),
        Kana::new(vec!["jyo"], "dyo", "デョ"),
        Kana::new(vec!["bya"], "bya", "ビャ"),
        Kana::new(vec!["byu"], "byu", "ビュ"),
        Kana::new(vec!["byo"], "byo", "ビョ"),
        Kana::new(vec!["pya"], "pya", "ピャ"),
        Kana::new(vec!["pyu"], "pyu", "ピュ"),
        Kana::new(vec!["pyo"], "pyo", "ピョ"),
        Kana::new(vec!["fa"], "fa", "ファ"),
        Kana::new(vec!["fi"], "fi", "フィ"),
        Kana::new(vec!["fe"], "fe", "フェ"),
        Kana::new(vec!["fo"], "fo", "フォ"),
        Kana::new(vec!["wi"], "wi", "ウィ"),
        Kana::new(vec!["we"], "we", "ウェ"),
        Kana::new(vec!["wo"], "uxo", "ウォ"),
        Kana::new(vec!["tza"], "tsa", "ツァ"),
        Kana::new(vec!["tze"], "tse", "ツェ"),
        Kana::new(vec!["tzi"], "tsi", "ツィ"),
        Kana::new(vec!["tzo"], "tso", "ツォ"),
        Kana::new(vec!["ti"], "thi", "ティ"),
        Kana::new(vec!["di"], "dhi", "ディ"),
        Kana::new(vec!["twu"], "twu", "トゥ"),
        Kana::new(vec!["dwu"], "dwu", "ドゥ"),
        Kana::new(vec!["she"], "she", "シェ"),
        Kana::new(vec!["je"], "je", "ジェ"),
        Kana::new(vec!["che"], "che", "チェ"),    
    ]
}
